{% set name = "wn" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wn-{{ version }}.tar.gz
  sha256: 9f4de116818c02a2eee7b830e76b58da3904f2eb8b1406f04d9eb7b071b6d7af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=3.4,<4
    - pip
  run:
    - python >=3.7
    - requests
    - tomli
    - typing-extensions

test:
  imports:
    - wn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/goodmami/wn
  summary: Wordnet interface library
  license: MIT
  license_file: LICENSE
  description: |
    Wn is a Python library for exploring information in wordnets. Install
    it from PyPI and download some data:

    ```console
    $ pip install wn
    $ python -m wn download oewn:2021  # the Open English WordNet 2021
    ```

    Then start exploring:

    ```python
    >>> import wn
    >>> en = wn.Wordnet('oewn:2021')  # Create Wordnet object to query
    >>> ss = en.synsets('win')[0]     # Get the first synset for 'win'
    >>> ss.definition()               # Get the synset's definition
    'be the winner in a contest or competition; be victorious'
    ```

    PyPI: [https://pypi.org/project/wn/](https://pypi.org/project/wn/)

  dev_url: https://github.com/goodmami/wn
  doc_url: https://wn.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - sugatoray
